_core:
  default_config_hash: DrYt8PcXA0xB3C3L1SvtefnkO5SwUonhY3n4Ld8yun4
entity_type_groups:
  node:
    recipe:
      basic: basic
      open_graph: open_graph
separator: ','
tag_trim_method: beforeValue
use_maxlength: true
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_abstract: null
  metatag_maxlength_og_site_name: null
  metatag_maxlength_og_title: null
  metatag_maxlength_og_description: null
tag_scroll_max_height: ''
tag_trim_end: '|.,-:;/+&([{"'''
